// T5 (plan evm-base-bsc): EVM RPC holdings client — OFFLINE, deterministic.
// `fetch` is stubbed with ABI-exact aggregate3 fixtures; no network, ever.
//
// Ground truth for the wire format: the golden calldata vector below is a REAL
// aggregate3 call captured from celo-org/celo-monorepo
// packages/op-tooling/exec/exec-upgrade.sh (case mainnet-succ-v102), generated by
// Safe tooling against Multicall3 — the encoder must reproduce it byte-for-byte.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  AGGREGATE3_SELECTOR,
  BALANCE_OF_SELECTOR,
  DECIMALS_SELECTOR,
  EvmRpcClient,
  MULTICALL3_ADDRESS,
  balanceOfCalldata,
  decodeAggregate3,
  decodeDecimals,
  decodeUint256,
  encodeAggregate3,
  evmEndpointList,
  evmRpcEndpoints,
  rawToTokenUnits,
} from '../src/providers/evm.js';

// Real Base contracts: USDC (6 decimals), WETH (18 decimals).
const WALLET = '0x1111111111111111111111111111111111111111';
const USDC = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const WETH = '0x4200000000000000000000000000000000000006';
const DEAD = '0x2222222222222222222222222222222222222222';

function u256(n: bigint | number): string {
  return BigInt(n).toString(16).padStart(64, '0');
}

/** Word i AFTER the 4-byte selector of an aggregate3 calldata hex. */
function wordOf(hex: string, i: number): string {
  return hex.slice(10 + i * 64, 10 + (i + 1) * 64);
}

/** Builds the exact `(bool success, bytes returnData)[]` hex Multicall3 returns. */
function aggregate3Result(rs: readonly { success: boolean; returnData: string }[]): string {
  const tuples = rs.map((r) => {
    const data = r.returnData.replace(/^0x/i, '');
    return [u256(r.success ? 1 : 0), u256(0x40), u256(data.length / 2), data.padEnd(Math.ceil(data.length / 64) * 64, '0')].join('');
  });
  const offs: string[] = [];
  let at = rs.length * 32;
  for (const t of tuples) {
    offs.push(u256(at));
    at += t.length / 2;
  }
  return `0x${u256(0x20)}${u256(rs.length)}${offs.join('')}${tuples.join('')}`;
}

const ok = (returnData: string): { success: boolean; returnData: string } => ({ success: true, returnData });
const fail = (): { success: boolean; returnData: string } => ({ success: false, returnData: '0x' });

interface RpcBody {
  method: string;
  params: [{ to: string; data: string }, string];
}

/** Fetch stub: records every hit; `respond(url, body)` decides the answer. */
function stubEvmRpc(
  hits: { url: string; body: RpcBody }[],
  respond: (url: string, body: RpcBody) => Response,
): typeof fetch {
  return (async (url: unknown, init?: { body?: string }) => {
    const body = JSON.parse(String(init?.body)) as RpcBody;
    hits.push({ url: String(url), body });
    return respond(String(url), body);
  }) as unknown as typeof fetch;
}

const ethOk = (result: string): Response =>
  new Response(JSON.stringify({ jsonrpc: '2.0', id: 1, result }), { status: 200 });

/** Captures log.warn/error stderr lines for the duration of `fn`. */
async function captureStderr(fn: () => Promise<void>): Promise<string[]> {
  const lines: string[] = [];
  const orig = process.stderr.write;
  try {
    process.stderr.write = ((chunk: unknown) => {
      lines.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    await fn();
  } finally {
    process.stderr.write = orig;
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Encoder — pinned to a real captured Multicall3 calldata (celo golden vector).

test('encodeAggregate3: byte-identical to real captured Multicall3 calldata (celo golden vector)', () => {
  // celo-org/celo-monorepo exec-upgrade.sh, case mainnet-succ-v102 (N=1):
  // target 0xfbac…af683, allowFailure=false, 0x44-byte callData 14f6b1a3(uint 0x2a, address 0xc5bd…de37).
  const golden =
    '0x82ad56cb' +
    u256(0x20) +
    u256(1) +
    u256(0x20) +
    '000000000000000000000000fbac162162f4009bb007c6debc36b1dac10af683' +
    u256(0) +
    u256(0x60) +
    u256(0x44) +
    '14f6b1a3' +
    u256(0x2a) +
    '000000000000000000000000c5bd131ceaeb72f15c66418bc2668332ab99de37' +
    '0'.repeat(56); // 68 data bytes pad to 96 (3 words)
  const mine = encodeAggregate3([
    {
      target: '0xfbac162162f4009bb007c6debc36b1dac10af683',
      allowFailure: false,
      callData: `0x14f6b1a3${u256(0x2a)}000000000000000000000000c5bd131ceaeb72f15c66418bc2668332ab99de37`,
    },
  ]);
  assert.equal(mine.toLowerCase(), golden.toLowerCase());
});

test('encodeAggregate3: two-call head/tail layout — offsets, bools, dynamic bytes, padding', () => {
  const hex = encodeAggregate3([
    { target: `0x${'aa'.repeat(20)}`, allowFailure: true, callData: '0x06fdde03' },
    { target: `0x${'bb'.repeat(20)}`, allowFailure: false, callData: '0x95d89b41' },
  ]);
  assert.equal(hex.slice(0, 10), `0x${AGGREGATE3_SELECTOR}`);
  assert.equal(BigInt(`0x${wordOf(hex, 0)}`), 0x20n); // array offset
  assert.equal(BigInt(`0x${wordOf(hex, 1)}`), 2n); // length
  assert.equal(BigInt(`0x${wordOf(hex, 2)}`), 0x40n); // tuple0 @ end of the 2-word offset area
  assert.equal(BigInt(`0x${wordOf(hex, 3)}`), 0xe0n); // tuple1 @ 0x40 + 160B tuple0
  assert.equal(wordOf(hex, 4), `000000000000000000000000${'aa'.repeat(20)}`);
  assert.equal(BigInt(`0x${wordOf(hex, 5)}`), 1n); // allowFailure=true
  assert.equal(BigInt(`0x${wordOf(hex, 6)}`), 0x60n); // bytes offset inside the tuple
  assert.equal(BigInt(`0x${wordOf(hex, 7)}`), 4n); // bytes length
  assert.equal(wordOf(hex, 8), '06fdde03' + '0'.repeat(56));
  assert.equal(wordOf(hex, 9), `000000000000000000000000${'bb'.repeat(20)}`);
  assert.equal(BigInt(`0x${wordOf(hex, 10)}`), 0n); // allowFailure=false
  assert.equal(wordOf(hex, 13), '95d89b41' + '0'.repeat(56));
  assert.equal((hex.length - 10) / 64, 14); // exactly 14 words, no slack
  assert.throws(() => encodeAggregate3([]), /no calls/);
});

test('balanceOfCalldata: selector 0x70a08231 + left-padded lowercase address', () => {
  assert.equal(balanceOfCalldata(`0x${'AB'.repeat(20)}`), `0x${BALANCE_OF_SELECTOR}${'000000000000000000000000'}${'ab'.repeat(20)}`);
  assert.throws(() => balanceOfCalldata('0x123'), /not an EVM address/);
});

// ---------------------------------------------------------------------------
// Decoder — strict; malformed input throws instead of decoding as "empty".

test('decodeAggregate3: ok/fail/ok batch — flags + returnData survive the walk', () => {
  const hex = aggregate3Result([ok(u256(1500000000000000000n)), fail(), ok(u256(7))]);
  const rs = decodeAggregate3(hex);
  assert.equal(rs.length, 3);
  assert.deepEqual(
    rs.map((r) => r.success),
    [true, false, true],
  );
  assert.equal(BigInt(rs[0]!.returnData), 1500000000000000000n);
  assert.equal(rs[1]!.returnData, '0x'); // failed sub-call, no data
  assert.equal(BigInt(rs[2]!.returnData), 7n);
});

test('decodeAggregate3: malformed hex throws (never a silent empty list)', () => {
  for (const bad of ['0x', '0xzz', '0x12345', u256(0x20), `${u256(0x20)}${u256(2)}${u256(0x40)}`]) {
    assert.throws(() => decodeAggregate3(bad), /invalid hex|malformed aggregate3/);
  }
  // a data-length word running past the end of the body
  const truncated = aggregate3Result([ok(u256(1))]).replace(/0000000000000000000000000000000000000000000000000000000000000020(.*)$/, `${u256(0x40)}$1`);
  assert.throws(() => decodeAggregate3(truncated), /malformed aggregate3/);
});

test('decodeUint256 / decodeDecimals / rawToTokenUnits: units + range edges', () => {
  assert.equal(decodeUint256(`0x${u256(1234567n)}`), 1234567n);
  assert.equal(decodeUint256('0x1234'), null); // not one ABI word
  assert.equal(decodeUint256('0x'), null);
  assert.equal(decodeDecimals(`0x${u256(18)}`), 18);
  assert.equal(decodeDecimals(`0x${u256(6)}`), 6);
  assert.equal(decodeDecimals(`0x${u256(0)}`), 0);
  assert.equal(decodeDecimals(`0x${u256(256)}`), null); // uint8 range only
  assert.equal(rawToTokenUnits(1500000000000000000n, 18), 1.5);
  assert.equal(rawToTokenUnits(1234567n, 6), 1.234567); // the 6-decimals case
  assert.equal(rawToTokenUnits(7n, 0), 7);
  assert.equal(rawToTokenUnits(5n, 18), 5e-18);
  // integer part never floats: > MAX_SAFE_INTEGER raw keeps every integer digit
  assert.equal(rawToTokenUnits(123456789012345678901234n, 18), 123456.78901234567);
});

// ---------------------------------------------------------------------------
// Client — one eth_call per wallet; request + response wire pinned.

test('EvmRpcClient: multi-token batch — ONE eth_call, balanceOf for every CA + decimals for the uncached, rows in token units', async () => {
  const origFetch = globalThis.fetch;
  const hits: { url: string; body: RpcBody }[] = [];
  try {
    globalThis.fetch = stubEvmRpc(hits, () =>
      ethOk(aggregate3Result([ok(u256(1500000000000000000n)), ok(u256(1234567n)), ok(u256(18)), ok(u256(6))])),
    );
    const client = new EvmRpcClient(() => ['https://evm.test']);
    const rows = await client.walletTokenHoldings(WALLET, 'base', [WETH, USDC]);

    assert.deepEqual(rows, [
      { ca: WETH, amount: 1.5 }, // 1500000000000000000 raw / 10^18
      { ca: USDC, amount: 1.234567 }, // 1234567 raw / 10^6 — the 6-decimals token
    ]);

    assert.equal(hits.length, 1); // the whole wallet is ONE request
    const { url, body } = hits[0]!;
    assert.equal(url, 'https://evm.test');
    assert.equal(body.method, 'eth_call');
    assert.equal(body.params[0].to, MULTICALL3_ADDRESS);
    assert.equal(body.params[1], 'latest');
    const data = body.params[0].data;
    assert.equal(data.slice(0, 10), `0x${AGGREGATE3_SELECTOR}`);
    assert.equal(Number(BigInt(`0x${wordOf(data, 1)}`)), 4); // 2 balanceOf + 2 decimals sub-calls
    assert.equal((data.match(new RegExp(BALANCE_OF_SELECTOR, 'g')) ?? []).length, 2);
    assert.equal((data.match(new RegExp(DECIMALS_SELECTOR, 'g')) ?? []).length, 2);
    assert.ok(data.includes(WETH.slice(2).toLowerCase()), 'WETH target missing from the batch');
    assert.ok(data.includes(USDC.slice(2).toLowerCase()), 'USDC target missing from the batch');
    assert.ok(data.includes(WALLET.slice(2)), 'wallet missing from balanceOf calldata');
    // every sub-call sets allowFailure=true: one dead token must not revert the batch
    assert.equal((data.match(new RegExp(u256(1), 'g')) ?? []).length >= 4, true);
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: a reverted sub-call (allowFailure=true) decodes as amount 0 — the others still decode', async () => {
  const origFetch = globalThis.fetch;
  try {
    globalThis.fetch = stubEvmRpc([], () =>
      ethOk(
        aggregate3Result([
          ok(u256(1500000000000000000n)),
          fail(), // DEAD token: balanceOf reverted (no code / non-standard)
          ok(u256(2234567n)),
          ok(u256(18)),
          ok(u256(18)),
          ok(u256(6)),
        ]),
      ),
    );
    const rows = await new EvmRpcClient(() => ['https://evm.test']).walletTokenHoldings(WALLET, 'base', [WETH, DEAD, USDC]);
    assert.deepEqual(rows, [
      { ca: WETH, amount: 1.5 },
      { ca: DEAD, amount: 0 }, // never dropped — the writer needs the 0 to delete the stale row
      { ca: USDC, amount: 2.234567 },
    ]);
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: balance>0 with decimals unavailable → skipped + logged (never a guessed scale); balance 0 still lands', async () => {
  const origFetch = globalThis.fetch;
  try {
    // decimals() sub-call reverts → no scale for WETH; USDC holds nothing, so
    // its missing decimals cannot corrupt anything (0 needs no scale).
    globalThis.fetch = stubEvmRpc([], () =>
      ethOk(aggregate3Result([ok(u256(1500000000000000000n)), ok(u256(0)), fail(), fail()])),
    );
    const client = new EvmRpcClient(() => ['https://evm.test']);
    const warns = await captureStderr(async () => {
      const r = await client.walletTokenHoldings(WALLET, 'base', [WETH, USDC]);
      assert.deepEqual(r, [{ ca: USDC, amount: 0 }]); // WETH skipped, USDC zero kept
    });
    assert.equal(
      warns.filter((l) => l.includes('decimals unavailable')).length,
      1,
      `expected exactly one decimals-unavailable warn, got: ${JSON.stringify(warns)}`,
    );
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: balanceOf returning non-uint256 data is skipped, not faked', async () => {
  const origFetch = globalThis.fetch;
  const warns: string[] = [];
  try {
    globalThis.fetch = stubEvmRpc([], () =>
      ethOk(aggregate3Result([{ success: true, returnData: '0x01' }, ok(u256(18))])),
    );
    const lines = await captureStderr(async () => {
      const rows = await new EvmRpcClient(() => ['https://evm.test']).walletTokenHoldings(WALLET, 'base', [WETH]);
      assert.deepEqual(rows, []);
    });
    warns.push(...lines);
    assert.equal(warns.some((l) => l.includes('non-uint256')), true);
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: decimals are cached per (chain, CA) — the second base call batches balanceOf only; bsc re-asks', async () => {
  const origFetch = globalThis.fetch;
  const hits: { url: string; body: RpcBody }[] = [];
  try {
    globalThis.fetch = stubEvmRpc(hits, (_url, body) => {
      // answer with exactly as many results as the request batched sub-calls
      const n = Number(BigInt(`0x${wordOf(body.params[0].data, 1)}`));
      const bal = ok(u256(1500000000000000000n));
      return ethOk(aggregate3Result(n === 1 ? [bal] : [bal, ok(u256(18))]));
    });
    const client = new EvmRpcClient(() => ['https://evm.test']);
    await client.walletTokenHoldings(WALLET, 'base', [WETH]);
    assert.equal((hits[0]!.body.params[0].data.match(new RegExp(DECIMALS_SELECTOR, 'g')) ?? []).length, 1);

    const rows2 = await client.walletTokenHoldings(WALLET, 'base', [WETH]);
    assert.deepEqual(rows2, [{ ca: WETH, amount: 1.5 }]); // served from the cached scale
    const data2 = hits[1]!.body.params[0].data;
    assert.equal(data2.includes(DECIMALS_SELECTOR), false, 'decimals() was re-asked despite the cache');
    assert.equal(Number(BigInt(`0x${wordOf(data2, 1)}`)), 1); // balanceOf only

    await client.walletTokenHoldings(WALLET, 'bsc', [WETH]); // same CA, other chain → cache key differs
    assert.equal((hits[2]!.body.params[0].data.match(new RegExp(DECIMALS_SELECTOR, 'g')) ?? []).length, 1);
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: dead primary → the keyless-style fallback serves the SAME call (plan R2); both dead → rejects WITHOUT the URL/key', async () => {
  const origFetch = globalThis.fetch;
  const hits: { url: string; body: RpcBody }[] = [];
  try {
    globalThis.fetch = stubEvmRpc(hits, (url) => {
      if (url.includes('dead')) return new Response('nope', { status: 503 });
      return ethOk(aggregate3Result([ok(u256(1500000000000000000n)), ok(u256(18))]));
    });
    const client = new EvmRpcClient(() => ['https://dead.example', 'https://live.example']);
    const rows = await client.walletTokenHoldings(WALLET, 'base', [WETH]);
    assert.deepEqual(rows, [{ ca: WETH, amount: 1.5 }]); // real data from endpoint #2, never dropped
    assert.deepEqual(hits.map((h) => h.url), ['https://dead.example', 'https://live.example']);

    // a JSON-RPC error body on the primary also fails over (not just HTTP statuses)
    hits.length = 0;
    globalThis.fetch = stubEvmRpc(hits, (url) => {
      if (url.includes('dead')) {
        return new Response(JSON.stringify({ jsonrpc: '2.0', id: 1, error: { code: -32005, message: 'limit exceeded' } }), {
          status: 429,
        });
      }
      return ethOk(aggregate3Result([ok(u256(5n)), ok(u256(18))]));
    });
    const rows2 = await new EvmRpcClient(() => ['https://dead.example', 'https://live.example']).walletTokenHoldings(
      WALLET,
      'base',
      [WETH],
    );
    assert.deepEqual(rows2, [{ ca: WETH, amount: 5e-18 }]);
    assert.deepEqual(hits.map((h) => h.url), ['https://dead.example', 'https://live.example']);

    // every endpoint dead → the LAST failure is rethrown, message carries no URL
    globalThis.fetch = stubEvmRpc([], () => new Response('nope', { status: 503 }));
    await assert.rejects(
      new EvmRpcClient(() => ['https://rpc.example/?key=SECRETTOKEN123']).walletTokenHoldings(WALLET, 'base', [WETH]),
      (e: Error) => /evm rpc eth_call failed \(base\)/.test(e.message) && !e.message.includes('SECRETTOKEN123') && !e.message.includes('rpc.example'),
    );
    // a thrown fetch (bad URL) must not echo the endpoint either
    globalThis.fetch = (async () => {
      throw new TypeError('fetch failed');
    }) as unknown as typeof fetch;
    await assert.rejects(
      new EvmRpcClient(() => ['https://rpc.example/?key=SECRETTOKEN123']).walletTokenHoldings(WALLET, 'base', [WETH]),
      (e: Error) => !e.message.includes('SECRETTOKEN123'),
    );
    // no endpoints at all → config-level error naming the env knobs
    await assert.rejects(
      new EvmRpcClient(() => []).walletTokenHoldings(WALLET, 'base', [WETH]),
      /no endpoint for base \(set BASE_RPC_URL\/BSC_RPC_URL\/ROBINHOOD_RPC_URL\)/,
    );
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('EvmRpcClient: input guards — non-EVM wallet throws, junk CAs are skipped + logged, empty cas never hits the wire', async () => {
  const origFetch = globalThis.fetch;
  const hits: { url: string; body: RpcBody }[] = [];
  try {
    globalThis.fetch = stubEvmRpc(hits, () => ethOk(aggregate3Result([ok(u256(1500000000000000000n)), ok(u256(18))])));
    const client = new EvmRpcClient(() => ['https://evm.test']);
    await assert.rejects(client.walletTokenHoldings('Fg9xK2mR7qT4vBn8cLd3', 'base', [WETH]), /not an EVM address/);
    assert.deepEqual(await client.walletTokenHoldings(WALLET, 'base', []), []);
    assert.equal(hits.length, 0); // nothing on the wire for guards that short-circuit

    const warns = await captureStderr(async () => {
      const rows = await client.walletTokenHoldings(WALLET, 'base', ['not-an-address', WETH]);
      assert.deepEqual(rows, [{ ca: WETH, amount: 1.5 }]); // the valid CA still decodes
    });
    assert.equal(warns.some((l) => l.includes('not an EVM address')), true);
  } finally {
    globalThis.fetch = origFetch;
  }
});

test('evmRpcEndpoints / evmEndpointList: env primary before the keyless fallback, deduped; sol has no EVM source', () => {
  // env unset in CI → the keyless endpoint is the whole list
  assert.deepEqual(evmRpcEndpoints('base'), ['https://mainnet.base.org']);
  assert.deepEqual(evmRpcEndpoints('bsc'), ['https://bsc-dataseed.binance.org']);
  assert.deepEqual(evmRpcEndpoints('robinhood'), ['https://rpc.mainnet.chain.robinhood.com']);
  assert.throws(() => evmRpcEndpoints('sol'), /no EVM RPC source/);
  // pure part: primary first, fallback appended once, duplicates collapsed
  assert.deepEqual(evmEndpointList('https://alchemy.test/v2/k', 'https://mainnet.base.org'), [
    'https://alchemy.test/v2/k',
    'https://mainnet.base.org',
  ]);
  assert.deepEqual(evmEndpointList('https://mainnet.base.org', 'https://mainnet.base.org'), ['https://mainnet.base.org']);
  assert.deepEqual(evmEndpointList('', 'https://mainnet.base.org'), ['https://mainnet.base.org']);
  assert.deepEqual(evmEndpointList('', undefined), []);
});
